// If different repo
node {
    def app

    stage('Clone repository') {
      

        checkout scm
    }

    stage('Update GIT') {
            script {
                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                    withCredentials([usernamePassword(credentialsId: 'github', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                        // github -> is github credentials from Jenkins.
                        //def encodedPassword = URLEncoder.encode("$GIT_PASSWORD",'UTF-8')
                        sh "git config user.email pnd.rns1@gmail.com"
                        sh "git config user.name Pradeep Kumar"
                        //sh "git switch master"
                        sh "cd kubernetesmanifest"
                        sh "cat deployment.yaml"
                        sh "sed -i 's+pndrns/k8s-gitops.*+pndrns/k8s-gitops:${DOCKERTAG}+g' deployment.yaml"
                        //in place update. "+"" is delimeter because container image has "/", else sed will fail
                        sh "cat deployment.yaml"
                        sh "git add ."
                        sh "git commit -m 'Done by Jenkins Job changemanifest: ${env.BUILD_NUMBER}'"
                        sh "git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/${GIT_USERNAME}/devops-rs.git HEAD:main"                  
                        
      }
    }
  }
}
}
