pipeline {
    agent any
    environment{
        DOCKERHUB_CREDS = credentials('dockerhub')
    }
    stages {
        stage('Clone Repo') {
            steps {
                checkout scm // scm is a spl variable which instructs checkout to clone the repo to appropriate Jenkins agent.
                sh 'ls *'
            }
        }
        stage('Build Image') {
            steps {
                //sh 'docker build -t pkumar-cloud/jenkinstest ./pushdockerimage/' (this will use the tag latest)
		sh 'docker build -t pndrns/jenkinstest:$BUILD_NUMBER ./pushdockerimage/'
            }
        }
        stage('Docker Login') {
            steps {
                //sh 'docker login -u $DOCKERHUB_CREDS_USR -p $DOCKERHUB_CREDS_PSW' (this will leave the password visible)
                sh 'echo $DOCKERHUB_CREDS_PSW | docker login -u $DOCKERHUB_CREDS_USR --password-stdin'                
                }
            }
        stage('Docker Push') {
            steps {
		//sh 'docker push pkumar-cloud/jenkinstest' (this will use the tag latest)    
                sh 'docker push pndrns/jenkinstest:$BUILD_NUMBER'
                }
            }
        }
    post {
		always {
			sh 'docker logout'
		}
	 }
    }

