node {
    def app

    stage('Clone repository') {
      

        checkout scm
    }

    stage('Build image') {
  
       app = docker.build("pndrns/k8s-gitops")
    }

    stage('Test image') {
  

        app.inside {
            sh 'echo "Tests passed"' // Dummy step, can be repalced with unit test.
        }
    }

    stage('Push image') {
        
        docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
            // dockerhub is id setup in Jenkins.
            app.push("${env.BUILD_NUMBER}") //Image is tagged with BUILD_NUMBER before pushing to repo.
        }
    }
    
    stage('Trigger ManifestUpdate') {
                echo "triggering updatemanifestjob"
                build job: 'updatemanifest', parameters: [string(name: 'DOCKERTAG', value: env.BUILD_NUMBER)]
        }
}
