pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'python:2-alpine'
                }
            }
            steps {
                sh 'python -m py_compile pythoncode/add2vals.py pythoncode/calc.py'  //Compile and convert to ByteCode -> .PYC.
                stash(name: 'compiled-results', includes: 'pythoncode/*.py*') //stash: Saving the Bytecode on Jenkins host. ByteCode will not be vanished after life cycle of docker agent finishes. 
                sh 'ls -l pythoncode'
            }
        }
        stage('Test') { 
            agent {
                docker {
                    image 'qnib/pytest' 
                }
            }
            steps {
                sh 'py.test --junit-xml test-reports/results.xml pythoncode/test_calc.py' //--junit-xml -> pytest generates junit results.xml report
                sh 'cat test-reports/results.xml'
            }
            post {
                always {
                    junit 'test-reports/results.xml' // junit archives the .xml report and exposes results via Jenkins interface.
                }
            }
        }
    }
}
