- hosts: webserver
  become: true
  vars:
    project_root: /var/www/html
  tasks:  
  - name: Install Apache Webserver
    yum: pkg=httpd state=present
  - name: Place the index file at project root
    copy: src=index.html dest={{ project_root }}/index.html
  - name: Enable Apache on system reboot
    service: name=httpd enabled=yes
    notify: restart apache
  handlers:
  - name: restart apache
    service: name=httpd state=restarted
